### ISSUE TITLE
allow custom engine instantiation

### ISSUE THREAD

**Issue by theluk** [RxNT/react-jsonschema-form-conditionals#61]
Due to https://github.com/RxNT/json-rules-engine-simplified/issues/31 it is currently not possible to use custom predicates. A quick hack would be to allow custom Engine instantiation as then one would be able to not pass a schema which would not trigger validation. and validation in this case is the reason for the ticket mentioned above.

**Comment by toanqc** [comment]
@theluk @mavarazy I need this change, I saw it merged to master but hasn't released yet.. so when I npm install, it still give me 0.3.12 instead of 0.3.13. Can you release 0.3.13?

**Comment by Dave-Rushabh** [comment]
Hello, i am trying to add custom engine to extend the predicates... @theluk, can you please share a code snippet if you could because even after adding the rulesRunner, my rules are not applied on the json form, i am getting in promise as schema, uiSchema and formData only... but how would i use the doRunRules to apply the rules on my form ??
